language: php

php:
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

env:
  - DB=sqlite
  - DB=mysql

before_install:
  - 'composer selfupdate --no-interaction'

install:
  - 'composer install --no-interaction --dev --prefer-source'
  
before_script:
  - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS bpmn;" -uroot; fi

script:
  - './vendor/bin/phpunit -c "./test/phpunit-$DB.xml" --coverage-text'

notifications:
  email: false

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly
