language: php

php:
  - 5.5
  - 5.6
  - hhvm
  - hhvm-nightly

env:
  - 'DB=sqlite LOWEST_DEPS=""'
  - 'DB=mysql LOWEST_DEPS=""'
  - 'DB=pgsql LOWEST_DEPS=""'
  - 'DB=sqlite LOWEST_DEPS="--prefer-lowest"'
  - 'DB=mysql LOWEST_DEPS="--prefer-lowest"'
  - 'DB=pgsql LOWEST_DEPS="--prefer-lowest"'
  
before_install:
  - 'composer selfupdate --no-interaction'

install:
  - 'composer update --no-interaction --dev --prefer-source $LOWEST_DEPS'
  
before_script:
  - 'if [[ "$DB" == "sqlite" ]]; then export DB_DSN="sqlite::memory:"; fi'
  - 'if [[ "$DB" == "mysql" ]]; then export DB_DSN="mysql:host=localhost;dbname=bpmn"; export DB_USERNAME="root"; mysql -e "CREATE DATABASE bpmn;" -uroot; fi'
  - 'if [[ "$DB" == "pgsql" ]]; then export DB_DSN="pgsql:host=localhost;dbname=bpmn"; export DB_USERNAME="postgres"; psql -c "CREATE DATABASE bpmn WITH ENCODING = ''UTF8'';" -U postgres; fi'

script:
  - './vendor/bin/phpunit -c "./test/phpunit.xml" --coverage-text'

notifications:
  email: false

matrix:
  allow_failures:
    - php: hhvm
    - php: hhvm-nightly
  exclude:
    - php: hhvm
      env: 'DB=pgsql LOWEST_DEPS=""'
    - php: hhvm-nightly
      env: 'DB=pgsql LOWEST_DEPS=""'
    - php: hhvm
      env: 'DB=pgsql LOWEST_DEPS="--prefer-lowest"'
    - php: hhvm-nightly
      env: 'DB=pgsql LOWEST_DEPS="--prefer-lowest"'
